
import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          200: "hsl(var(--primary-200))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          900: "hsl(var(--primary-900))",
          950: "hsl(var(--primary-950))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--secondary-50))",
          100: "hsl(var(--secondary-100))",
          200: "hsl(var(--secondary-200))",
          300: "hsl(var(--secondary-300))",
          400: "hsl(var(--secondary-400))",
          500: "hsl(var(--secondary-500))",
          600: "hsl(var(--secondary-600))",
          700: "hsl(var(--secondary-700))",
          800: "hsl(var(--secondary-800))",
          900: "hsl(var(--secondary-900))",
          950: "hsl(var(--secondary-950))",
        },
        tertiary: {
          DEFAULT: "hsl(var(--tertiary))",
          foreground: "hsl(var(--tertiary-foreground))",
          50: "hsl(var(--tertiary-50))",
          100: "hsl(var(--tertiary-100))",
          200: "hsl(var(--tertiary-200))",
          300: "hsl(var(--tertiary-300))",
          400: "hsl(var(--tertiary-400))",
          500: "hsl(var(--tertiary-500))",
          600: "hsl(var(--tertiary-600))",
          700: "hsl(var(--tertiary-700))",
          800: "hsl(var(--tertiary-800))",
          900: "hsl(var(--tertiary-900))",
          950: "hsl(var(--tertiary-950))",
        },
        quaternary: {
          DEFAULT: "hsl(var(--quaternary))", // Vert
          foreground: "hsl(var(--quaternary-foreground))",
          50: "hsl(var(--quaternary-50))",
          100: "hsl(var(--quaternary-100))",
          200: "hsl(var(--quaternary-200))",
          300: "hsl(var(--quaternary-300))",
          400: "hsl(var(--quaternary-400))",
          500: "hsl(var(--quaternary-500))",
          600: "hsl(var(--quaternary-600))",
          700: "hsl(var(--quaternary-700))",
          800: "hsl(var(--quaternary-800))",
          900: "hsl(var(--quaternary-900))",
          950: "hsl(var(--quaternary-950))",
        },
        quinary: {
          DEFAULT: "hsl(var(--quinary))",   // Jaune
          foreground: "hsl(var(--quinary-foreground))",
          50: "hsl(var(--quinary-50))",
          100: "hsl(var(--quinary-100))",
          200: "hsl(var(--quinary-200))",
          300: "hsl(var(--quinary-300))",
          400: "hsl(var(--quinary-400))",
          500: "hsl(var(--quinary-500))",
          600: "hsl(var(--quinary-600))",
          700: "hsl(var(--quinary-700))",
          800: "hsl(var(--quinary-800))",
          900: "hsl(var(--quinary-900))",
          950: "hsl(var(--quinary-950))",
        },
        senary: {
          DEFAULT: "hsl(var(--senary))",     // Gris
          foreground: "hsl(var(--senary-foreground))",
          50: "hsl(var(--senary-50))",
          100: "hsl(var(--senary-100))",
          200: "hsl(var(--senary-200))",
          300: "hsl(var(--senary-300))",
          400: "hsl(var(--senary-400))",
          500: "hsl(var(--senary-500))",
          600: "hsl(var(--senary-600))",
          700: "hsl(var(--senary-700))",
          800: "hsl(var(--senary-800))",
          900: "hsl(var(--senary-900))",
          950: "hsl(var(--senary-950))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-down": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.5s ease-out",
        "fade-down": "fade-down 0.5s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
} satisfies Config;
