// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndgyijggnmslzosfprpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ3lpamdnbm1zbHpvc2ZwcnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMzc2NDksImV4cCI6MjA1NDcxMzY0OX0.8Cfew1b5dLawEllUkKSnVhQtqODkvkn7RPpMk_sHiM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);