
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndgyijggnmslzosfprpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ3lpamdnbm1zbHpvc2ZwcnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMzc2NDksImV4cCI6MjA1NDcxMzY0OX0.8Cfew1b5dLawEllUkKSnVhQtqODkvkn7RPpMk_sHiM4";

// Configuration améliorée pour le client Supabase
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    global: {
      headers: {
        'X-Client-Info': 'BudgetWizard/1.0'
      }
    }
  }
);

// Activer la surveillance en temps réel pour la table des crédits
supabase.from('credits')
  .on('*', (payload) => {
    console.log('Changement temps réel détecté dans la table credits:', payload);
  })
  .subscribe();
